universe                = docker
docker_image            = pytorch/pytorch:2.4.0-cuda12.1-cudnn9-runtime
initialdir              = /home/dani00003/causally-reliable-cbm_graph_pertub
executable              = /home/dani00003/causally-reliable-cbm_graph_pertub/server_scripts/graph_sanity_scripts/celeba/run_c2bm_celeba_topology.sh
arguments               = $(GRAPH_SEED)

output                  = /home/dani00003/causally-reliable-cbm_graph_pertub/server_scripts/graph_sanity_scripts/celeba/topology.$(ClusterId).$(ProcId).out
error                   = /home/dani00003/causally-reliable-cbm_graph_pertub/server_scripts/graph_sanity_scripts/celeba/topology.$(ClusterId).$(ProcId).err
log                     = /home/dani00003/causally-reliable-cbm_graph_pertub/server_scripts/graph_sanity_scripts/celeba/topology.$(ClusterId).log

request_GPUs            = 1
request_CPUs            = 8
request_memory           = 32G
requirements             = UidDomain == "cs.uni-saarland.de"
+WantGPUHomeMounted      = true

queue GRAPH_SEED from (
    1
    2
    3
    4
    5
)
